//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShowRoom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.Clients = new HashSet<Client>();
        }
    
        public int Id { get; set; }
        public int CarBrandId { get; set; }
        public string Model { get; set; }
        public double Load { get; set; }
        public string Axel { get; set; }
        public double EngineCapacity { get; set; }
        public double FuelPerHunderdKm { get; set; }
        public int ProductionYear { get; set; }
        public double Price { get; set; }
        public string GearBox { get; set; }
    
        public virtual CarBrand CarBrand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients { get; set; }
    }
}
