//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShowRoom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int Id { get; set; }
        public int CarId { get; set; }
        public string FullName { get; set; }
        public string HomeAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string DateBuy { get; set; }
        public Nullable<double> BuyPrice { get; set; }
        public Nullable<double> ServicePercent { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
